language: generic

deploy:
  provider: s3
  access_key_id: AKIAINEN6GW4S4CIRD7Q
  secret_access_key:
    secure: MpG5bF7Xjmfxe/Oj8L+shpXVEJpbICWgyh0yGZO8tepXAb4zzhD2/2ST5cUVjbH6ToYjEI7WVOqbuRYo0JGOPoVuktsno5mt+m4xc4mFRKYZlUHldlmmUI5HBrdzRgwkWcRF57PJV5dIeR9iG7khQB2NElRonJawT+EFQHA+dY2NpoQ3df9RkX63O/dz+/MT/G4g3RcSgajv2hJHHSTU78Mbg97DXUlOSt1YHRTdJ/3FzBwXy6wR9WfJCDrt029oInZlh3JdK3y+tMWOjLD09XZv7joNNGjrA6S1yzKtezVYgW0EIp02hAsKpE+XebvSfOjSD4rWQ72zb6sufSjAeQMCVuyYXlWvzGzwu5J8+7Nv05hYsdCUQL6vCn4ujhfI4cmbAhCRBvUwq365o4xC7MC8xjJQvZfoCgNX3wD5dQrS+W5nYufhSNxtnPRV8aR1+cmpabDFnL+ZTnNnMTIu2nHex869WUrWZEETmy+LKwSBTiKyIRaWVvQdQw/FImtX3akcGpRN8sgzKZ+QUiB5cLaF7awCL4MgpWmhwkjm1mFFDLyBAswBHRLybLKnQYU9TPBy7fs5CmmmsDMm+6DREv059h+1DZQ9yWVxiDon94+qrY1GfRbqMghpn5wywapWN9JXd5ugRCSSh6XJy5VUBSGc3p60OJme1k0lKCKZDzg=
  bucket: olanod.com
  region: eu-central-1
  skip_cleanup: true
  acl: public_read
